package com.example.accessingdatamysql;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.json.JSONObject;

@RestController	// This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
@CrossOrigin(origins = "http://localhost:8081")
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private Pins_testRepository pins_testRepository;

	@PostMapping(path="/locations") // Map ONLY POST Requests
	public @ResponseBody String addNewPin (@RequestBody String request) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		JSONObject jsonObj = new JSONObject(request);
  		  double longitude = jsonObj.getDouble("longitude");
  		  double latitude = jsonObj.getDouble("latitude");
   		 System.out.println("Longitude: " + longitude);
   		 System.out.println("Latitude: " + latitude);
		
		Pins_test n = new Pins_test();
		n.setLongitude(longitude);
		n.setLatitude(latitude);
		pins_testRepository.save(n);
		
		return "Saved";
	}

	@GetMapping(path="/show")
	public @ResponseBody ArrayList<double[]> getAllPins() {
		// This returns a JSON or XML with the users
		//return pins_testRepository.findAll();
		/* 
		List<Map<String, Object>> result = new ArrayList<>();
		for(Pins_test pin : pins_testRepository.findAll()) {
			Map<String, Object> pinData = new HashMap<>();
			pinData.put("pin_id", pin.getPin_id());
			pinData.put("latitude", pin.getLatitude());
			pinData.put("longitude", pin.getLongitude());

			System.out.println("Longitude: " + pin.getLatitude());
   		    System.out.println("Latitude: " + pin.getLongitude());
			result.add(pinData);

		}
		*/
		ArrayList<double[]> list = new ArrayList<double[]>();
		for(Pins_test pin : pins_testRepository.findAll()) {
			double[] temp=new double[2];
			temp[0]=pin.getLongitude();
			temp[1]=pin.getLatitude();
			list.add(temp);
		}

		return list;
	}
}

